### ISSUE TITLE
shipping prices need to be edited

### ISSUE THREAD

**Issue by 41ylogab** [penguinsource/pokemon_pac#27]
we need to talk about this. i have values written down etc...and i think i have the file too. do this over the phone = way easier

**Comment by penguinsource** [comment]
this is done - still need to have special conditions tho..

**Comment by penguinsource** [comment]
per your text

Canada NON PSA:

if 0-49.99$

= 2$

if 50-99.99$

= 7.$

if 100$+

= 13$ + 1.5$ for each hundred above 100



USA NON PSA:

if 0-49.99$

= 3$

if cartweight < 150g

=4.5 + 1.5$ for each hundred

if cartweight 150-250g

= 7.5 + 1.5$ for each hundred

if cart weight 250-500g

= 12$ + 1.5$ for each hundred



INTERNATIONAL NON PSA:

if < 50$

= 6$

if cartweight < 150g

= 8.25 + 1.5$ for each hundred

if cartweight 150-250g

= 12 + 1.5 for each hundred

if 250g-500g 

= 20$ + 1.5$ for each hundred





PSA CARDS:

Canada:

if under 50$
if 1-2 items: 3$
if 3-4 items: 6$
if 5+ items: 15$

if over 50$ (add 1.5$ for each hundred over 100$)
if 1-2 items: 7.5$
if 3-4 items: 10.5$
if 5+ items: 20$

FOR USA:

if under 50$
if 1-2 items: 4$
if 3-4 items: 10$
if 5+ items: 20$

if over 50$ (add 1.5$ for each hundred over 100$)
if 1-2 items: 5.25$
if 3-4 items: 12$
if 5+ items: 25$

For international:

if under 50$
1-2 items: 7$
3-4 items: 13$
5+ items: 25$

if over 50$ (add 1.5$ for each hundred over 100$)
1-2 items: 8.5$
3-4 items: 14.5$
5+ items: 25$


COUNTRIES WE SHIP TO INTERNATIONALLY:

Argentina, Australia, Austria, Bahamas, Bangladesh, Barbados, Belgium, Bermuda, 
Canada, Chile, China, Costa Rica, Croatia, Cyprus, Czech Republic, Denmark, 
Dominican Republic, Egypt, El Salvador, Estonia, Finland, France, Germany, Greece, 
Greenland, Guatemala, Hong Kong, Hungary, Iceland, Ireland, Israel, Italy, Jamaica, 
Japan, Korea, Republic of, Luxembourg, Mexico, Morocco, Netherlands, New Zealand, 
Norway, Poland, Portugal, Romania, Samoa, Singapore, South Africa, Spain, Sweden, 
Switzerland, Taiwan, Turkey, United Kingdom, United States, Uruguay.

PUT CANADA, USA, UK at the top as first three from drop down, then list them alpha
